/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import '@stencil/core';




export namespace Components {

  interface DynamicUsertaskComponent {
    'usertask': string;
  }
  interface DynamicUsertaskComponentAttributes extends StencilHTMLAttributes {
    'onSubmitted'?: (event: CustomEvent) => void;
    'usertask'?: string;
  }

  interface BooleanFormField {}
  interface BooleanFormFieldAttributes extends StencilHTMLAttributes {}

  interface DateFormField {}
  interface DateFormFieldAttributes extends StencilHTMLAttributes {}

  interface EnumFormField {}
  interface EnumFormFieldAttributes extends StencilHTMLAttributes {}

  interface LongFormField {}
  interface LongFormFieldAttributes extends StencilHTMLAttributes {}

  interface NumberFormField {}
  interface NumberFormFieldAttributes extends StencilHTMLAttributes {}

  interface StringFormField {}
  interface StringFormFieldAttributes extends StencilHTMLAttributes {}
}

declare global {
  interface StencilElementInterfaces {
    'DynamicUsertaskComponent': Components.DynamicUsertaskComponent;
    'BooleanFormField': Components.BooleanFormField;
    'DateFormField': Components.DateFormField;
    'EnumFormField': Components.EnumFormField;
    'LongFormField': Components.LongFormField;
    'NumberFormField': Components.NumberFormField;
    'StringFormField': Components.StringFormField;
  }

  interface StencilIntrinsicElements {
    'dynamic-usertask-component': Components.DynamicUsertaskComponentAttributes;
    'boolean-form-field': Components.BooleanFormFieldAttributes;
    'date-form-field': Components.DateFormFieldAttributes;
    'enum-form-field': Components.EnumFormFieldAttributes;
    'long-form-field': Components.LongFormFieldAttributes;
    'number-form-field': Components.NumberFormFieldAttributes;
    'string-form-field': Components.StringFormFieldAttributes;
  }


  interface HTMLDynamicUsertaskComponentElement extends Components.DynamicUsertaskComponent, HTMLStencilElement {}
  var HTMLDynamicUsertaskComponentElement: {
    prototype: HTMLDynamicUsertaskComponentElement;
    new (): HTMLDynamicUsertaskComponentElement;
  };

  interface HTMLBooleanFormFieldElement extends Components.BooleanFormField, HTMLStencilElement {}
  var HTMLBooleanFormFieldElement: {
    prototype: HTMLBooleanFormFieldElement;
    new (): HTMLBooleanFormFieldElement;
  };

  interface HTMLDateFormFieldElement extends Components.DateFormField, HTMLStencilElement {}
  var HTMLDateFormFieldElement: {
    prototype: HTMLDateFormFieldElement;
    new (): HTMLDateFormFieldElement;
  };

  interface HTMLEnumFormFieldElement extends Components.EnumFormField, HTMLStencilElement {}
  var HTMLEnumFormFieldElement: {
    prototype: HTMLEnumFormFieldElement;
    new (): HTMLEnumFormFieldElement;
  };

  interface HTMLLongFormFieldElement extends Components.LongFormField, HTMLStencilElement {}
  var HTMLLongFormFieldElement: {
    prototype: HTMLLongFormFieldElement;
    new (): HTMLLongFormFieldElement;
  };

  interface HTMLNumberFormFieldElement extends Components.NumberFormField, HTMLStencilElement {}
  var HTMLNumberFormFieldElement: {
    prototype: HTMLNumberFormFieldElement;
    new (): HTMLNumberFormFieldElement;
  };

  interface HTMLStringFormFieldElement extends Components.StringFormField, HTMLStencilElement {}
  var HTMLStringFormFieldElement: {
    prototype: HTMLStringFormFieldElement;
    new (): HTMLStringFormFieldElement;
  };

  interface HTMLElementTagNameMap {
    'dynamic-usertask-component': HTMLDynamicUsertaskComponentElement
    'boolean-form-field': HTMLBooleanFormFieldElement
    'date-form-field': HTMLDateFormFieldElement
    'enum-form-field': HTMLEnumFormFieldElement
    'long-form-field': HTMLLongFormFieldElement
    'number-form-field': HTMLNumberFormFieldElement
    'string-form-field': HTMLStringFormFieldElement
  }

  interface ElementTagNameMap {
    'dynamic-usertask-component': HTMLDynamicUsertaskComponentElement;
    'boolean-form-field': HTMLBooleanFormFieldElement;
    'date-form-field': HTMLDateFormFieldElement;
    'enum-form-field': HTMLEnumFormFieldElement;
    'long-form-field': HTMLLongFormFieldElement;
    'number-form-field': HTMLNumberFormFieldElement;
    'string-form-field': HTMLStringFormFieldElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
